services:
  qbittorrent-qui:
    image: braingremlin/qbittorrent-qui:latest
    container_name: qbittorrent-qui
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
      - WEBUI_PORT=${WEBUI_PORT:-8080}
      - TORRENTING_PORT=${TORRENTING_PORT:-6881}
      - QUI_PORT=${QUI_PORT:-7476}
    stop_grace_period: 15m
    volumes:
      - ${CONFIG_DIR:-config}:/config
      - ${WATCH_FOLDER:-watch}:/watch #optional
      - ${INCOMPLETE_FOLDER:-incomplete}:/incomplete # needed ???
      - /volume2/media/download:/media01/download
      - /volume3/media02/download:/media02/download
      - /volume4/media03/download:/media03/download
    ports:
      - ${WEBUI_PORT}:8080
      - ${TORRENTING_PORT}:${TORRENTING_PORT}
      - ${TORRENTING_PORT}:${TORRENTING_PORT}/udp
      - ${QUI_PORT}:7476
    restart: unless-stopped
    networks:
      media-bridge:
    security_opt:
      - no-new-privileges:true

networks:
  media-bridge:
    driver: bridge
    name: media-bridge  

volumes:
  config:
  incomplete:
  watch: